"""empty message

Revision ID: 9118d598d0ab
Revises: 
Create Date: 2021-01-02 11:33:47.287195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9118d598d0ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dailyrecord', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dailyrecord', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('paste', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'approved',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'approved',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('paste', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dailyrecord', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dailyrecord', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
